### ISSUE TITLE
llama-guard eval scripts

### ISSUE THREAD

**Issue by alexbie98** [meta-llama/PurpleLlama#10]
Do you plan to release the eval scripts for the results in the paper and here (https://github.com/facebookresearch/PurpleLlama/blob/main/Llama-Guard/MODEL_CARD.md) for openai moderation and toxicchat?

**Comment by ujjwalkarn** [comment]
Hi there, Llama recipes provides a [script for running Llama Guard inference](https://github.com/meta-llama/llama-recipes/blob/main/recipes/responsible_ai/llama_guard/inference.py). We then use sklearn's precision_score, recall_score, f1_score, average_precision_score to compute the metrics. Please let us know if this doesn't help!

**Comment by dirtycomputer** [comment]
How to get score like this:`https://platform.openai.com/docs/guides/moderation/overview`
<img width="403" alt="截屏2024-05-29 23 46 33" src="https://github.com/meta-llama/PurpleLlama/assets/48406770/7694ac35-bb0a-4d03-9532-15093602bc23">
