### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by AaronShenny** [meta-llama/PurpleLlama#11]
![image](https://github.com/facebookresearch/PurpleLlama/assets/103166950/25a0cffa-cf8f-4698-adc6-34f08bf12e55)
this error cam when i run \CybersecurityBenchmarks\benchmark>python run.py

**Comment by SimonWan** [comment]
Running from the repo's root dir with `python3 -m CybersecurityBenchmarks.benchmark.run` should resolve this issue
