### ISSUE TITLE
got error to run download.sh download.sh: line 1: payload:allShortcutsEnabled:false: command not found

### ISSUE THREAD

**Issue by liqi6811** [meta-llama/PurpleLlama#13]
I am using wsl in windows machine, I can use ```wget``` to download the ```download.sh``` file, but when I use ```bash download.sh``` to run the file, I got below error: 

```
download.sh: line 1: payload:allShortcutsEnabled:false: command not found
```

I have tried ```chmod +x donwload.sh``` , but still have the same error. 

What should I do? Thanks

**Comment by ujjwalkarn** [comment]
Hi, could you try the `download.sh` for the recently released [Llama-Guard2](https://github.com/meta-llama/PurpleLlama/tree/main/Llama-Guard2)? Closing this for now, but please reopen if issue persists.
