### ISSUE TITLE
./download.sh: 13: Bad substitution

### ISSUE THREAD

**Issue by Galling-Yu** [meta-llama/PurpleLlama#20]
When downloading LICENSE and Acceptable Usage Policy,  it echos "./download.sh: 13: Bad substitution"

**Comment by ujjwalkarn** [comment]
Hi, could you try downloading the recently released [Llama-Guard2](https://github.com/meta-llama/PurpleLlama/tree/main/Llama-Guard2)? Closing this for now, but please reopen if issue persists.
