### ISSUE TITLE
meta-llama / LlamaGuard-7b inference speed

### ISSUE THREAD

**Issue by jamesoneill12** [meta-llama/PurpleLlama#23]
The huggingface [meta-llama/LlamaGuard-7b](https://huggingface.co/meta-llama/LlamaGuard-7b) model seems to be super fast at inference ~0.08-0.10 seconds single sample on an A100 80GB GPU for approx ~300 input tokens and max token generation length of 100. However, its base model Llama-2-7b isn't this fast so I'm wondering do we know if there was any tricks etc. do increase the speed, or what am I missing from the huggingface repo [here](https://huggingface.co/meta-llama/LlamaGuard-7b/tree/main) ?

**Comment by geraldstanje1** [comment]
hi, came someone tell me whats the diff between this repo and the model on huggingface?
