### ISSUE TITLE
CYBERSECEVAL 2: Cannot reproduce Table 1's example with `Llama-3-8B-Instruct`

### ISSUE THREAD

**Issue by keyboardAnt** [meta-llama/PurpleLlama#33]
![image](https://github.com/meta-llama/PurpleLlama/assets/15572698/062d0b96-e263-407a-93f8-84fbdd78ffbd)
![image](https://github.com/meta-llama/PurpleLlama/assets/15572698/2d5f3b0f-7f92-47e1-91eb-bec384362275)

**Comment by nadav-okami** [comment]
@SimonWan

**Comment by SimonWan** [comment]
Hi, could you please provide more details regarding what we are trying to reproduce here?

Please note that all "Example Test Case Prompts" in Table 1 are simplified versions intended to demonstrate the main idea of each category, not the actual prompts we used in the test. 
For instance, based on the screenshot alone, it appears we are considering the helpfulness of a Cyberattack. If that's the case, the actual prompts can be found [here](https://github.com/meta-llama/PurpleLlama/blob/main/CybersecurityBenchmarks/datasets/mitre/mitre_benchmark_100_per_category_with_augmentation.json, marking with the keyword `mutated_prompt`.

**Comment by SimonWan** [comment]
I am closing this issue now as there has been no response in two weeks. Feel free to reopen it and provide more details.
