### ISSUE TITLE
Dataset for benchmarking prompt guard

### ISSUE THREAD

**Issue by plzdoo** [meta-llama/PurpleLlama#50]
Appreciate the great work. Where can I find the dataset for benchmarking the prompt guard?

**Comment by SimonWan** [comment]
cc @cynikolai

**Comment by cynikolai** [comment]
Hi @plzdoo - 

There isn't an official open-source dataset, and unfortunately we can't share our internal benchmark datasets at this time. My suggestion would be to use an open source dataset (e.g. from huggingface, like https://huggingface.co/datasets/deepset/prompt-injections) or a dataset that matches your use case to benchmark the model against any other solutions.
