### ISSUE TITLE
How is `gen_consolidated_rules.py` supposed to work?

### ISSUE THREAD

**Issue by Co1lin** [meta-llama/PurpleLlama#58]
Hi, I think the ICD loads rules from `CodeShield/insecure_code_detector/rules/semgrep/_generated_` to analyze the code. If I change the content of some rules, or add some new rules, how to use `gen_consolidated_rules.py` to generate this folder? What's the correct command to execute this script?

**Comment by laurendeason** [comment]
Apologies for the delayed reply!  This script (gen_consolidated_rules.py) is not needed, and has since been removed from the codebase.  To edit or add more rules you can simply manually add or edit rules in the appropriate folder within CodeShield/insecure_code_detector/rules/
