### ISSUE TITLE
Running CyberSecEval on Windows

### ISSUE THREAD

**Issue by carina-ding** [meta-llama/PurpleLlama#62]
Hi, Thank you very much for making this amazing toolkit open sourced!

It seems that there are some errors while trying to run CyberSecEval on Windows. May I check with you whether running CyberSecEval on Windows is supported?

Thank you!

**Comment by laurendeason** [comment]
Yes, it should be supported.  Maybe double check your environment setup and the path from which you are running?  Otherwise, can you share more detail on the errors you are running into?

**Comment by laurendeason** [comment]
marking as resolved, please feel free to re-open if you are still running into issues and can share some additional detail about any errors you are encountering!
